title: Beta Beta
email: me@betab.io
description: Tecnologia descomplicada, por Beta Brandão.
baseurl: "" 
url: "https://betab.io" 
twitter_username: betabrandaorio
github_username:  betabrandao
paginate: 5
theme-dark: false
plugins: [jekyll-paginate, kramdown]
google_analytics:  UA-117116291-1
markdown: kramdown
permalink: /:title/