title: Roberta Brandão
email: blog@robertabrandao.com.br   
description: Elixir em Português em algumas coisas que posso achar importante.
baseurl: "" 
url: "https://robertabrandao.com.br"
keybase_username: betabrandaorio
github_username:  betabrandao
linkedin_username: betabrandao
paginate: 5
theme-dark: false
plugins: [jekyll-paginate, kramdown]
google_analytics:  
markdown: kramdown
permalink: /:categories/:title/

collections:
  - slides

exclude:
  - reveal.js/plugin/markdown/example.html
  - reveal.js/plugin/markdown/example.md
  - reveal.js/css/theme/README.md
  - slides/index.md
