title: Beta B
email: me@betab.io
description: Um local para estudar e aprender (escrevendo) 
baseurl: "" 
url: "https://betab.io" 
twitter_username: betabrandaorio
github_username:  betabrandao
paginate: 5
theme-dark: false
plugins: [jekyll-paginate, kramdown]
google_analytics:  UA-117116291-1
markdown: kramdown
permalink: /:title/