title: Beta Brandão
email: me@betab.io
description: Um local para estudar e aprender (escrevendo) 
baseurl: "/betab.github.io" 
url: "https://betab.io" 
twitter_username: betabrandaorio
github_username:  betabrandao
paginate: 5
theme-dark: false
plugins: [jekyll-paginate, kramdown]

markdown: kramdown
