title: Roberta Brandão
email: blog@robertabrandao.com.br   
description: Porque só aprendo de verdade escrevendo.
baseurl: "" 
url: "https://robertabrandao.com.br"
keybase_username: betabrandaorio
twitter_username: betabrandaorio
github_username:  betabrandao
linkedin_username: betabrandao
paginate: 5
theme-dark: false
plugins: [jekyll-paginate, kramdown]
google_analytics:  UA-117116291-1
markdown: kramdown
permalink: /:title/

#collection
collections:
  - slides

exclude:
  - reveal.js/plugin/markdown/example.html
  - reveal.js/plugin/markdown/example.md
  - slides/index.md
